version: '3'
services:

  elasticsearch:
    image: elasticsearch:7.12.0
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - cluster.name=elasticsearch
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - cluster.routing.allocation.disk.threshold_enabled=false
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=PassW0rd
        #      - discovery.type=single-node
        #      - xpack.security.audit.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    networks: ['stack']

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.12.0
    container_name: apm-server
    ports:
      - 8200:8200
    volumes:
      - ./apm-server.yml:/usr/share/apm-server/apm-server.yml
    networks:
      - stack
    depends_on:
      - elasticsearch


        #logstash:
        #image: docker.elastic.co/logstash/logstash:7.13.3
        #environment:
        #- ELASTICSEARCH_USERNAME=elastic
        #- ELASTICSEARCH_PASSWORD=PassW0rd
        #ports:
        #- 5044:5044
    #volumes:
    #  - ./logstash.yml:/usr/share/logstash/config/logstash.yml
    #  - ./logstash-elastic.conf:/usr/share/logstash/pipeline/logstash.conf
    #networks: ['stack']
    #depends_on: ['elasticsearch']


  kibana:
    image: kibana:7.12.0
    ports: ['5601:5601']
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=PassW0rd
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks: ['stack']
    links: ['elasticsearch']
    depends_on: ['elasticsearch']

networks:
  stack: {}
